version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: ["/opt/venv/bin/python", "-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678"]
    command: ["jupyter", "notebook", "--notebook-dir=/notebooks", "--ip=0.0.0.0", "--port=8888", "--no-browser"]
    ports:
      - 8888:8888
      - 5678:5678
    volumes:
      - ./notebooks:/notebooks
    user: "appuser"
