version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: /usr/local/bin/python3
    command: ["-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678", "/app/app.py"]
    ports:
      - 8888:8888
      - 5678:5678
    volumes:
      - .:/app
    user: "appuser"
