version: '3.4'

services:
  app:
    environment:
      - PYTHONUNBUFFERED=1
    entrypoint: /usr/local/bin/python3.11
    command: ["-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678", "/app/app.py"]
    ports:
      - 8888:8888
      - 5678:5678
