# This deployment setting assumes that a persistent disk was created in Google Cloud Platform (GCP) beforehand.
# Visit the following link if you need instructions on creating a persistent disk in GCP: https://cloud.google.com/compute/docs/disks/add-persistent-disk?hl=en
# Execute the following command by typing "kubectl apply -f deployment.yaml" in your terminal or Linux virtual machine.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quantumworkspace
  labels:
    app: quantumworkspace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quantumworkspace
  template:
    metadata:
      labels:
        app: quantumworkspace
    spec:
      containers:
      - name: quantumworkspace
        image: elijun831/quantumworkspace:2.0.4
        ports:
        - containerPort: 443
        volumeMounts:
        - mountPath: /mnt/disks/pv
          name: gce-pd
        readinessProbe:
          httpGet:
            path: '/'
            port: 443
          initialDelaySeconds: 7
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 7
        livenessProbe:
          httpGet:
            path: '/'
            port: 443
          initialDelaySeconds: 120
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 7
      volumes:
      - name: gce-pd
        gcePersistentDisk:
          pdName: qtumdisk
          fsType: ext4
          readOnly: true
