# This deployment setting assumes that a readWriteMany NFS volume was created in Google Cloud Platform (GCP) beforehand.
# Visit the following link if you need instructions on creating a NFS volume: https://cloud.google.com/architecture/partners/netapp-cloud-volumes/creating-nfs-volumes
# Execute the following command by typing "kubectl apply -f deployment.yaml" in your terminal or Linux virtual machine.

metadata:
  name: quantumworkspace-deployment
  labels:
    app: quantumworkspace-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quantumworkspace-deployment
  template:
    metadata:
      labels:
        app: quantumworkspace-deployment
    spec:
      containers:
      - name: quantumworkspace
        image: elijun831/quantumworkspace:2.0.4
        ports:
        - containerPort: 443
        volumeMounts:
          - mountPath: /nfs-qtum
            name: qtumnfs
        readinessProbe:
          httpGet:
            path: '/'
            port: 443
          initialDelaySeconds: 7
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 7
        livenessProbe:
          httpGet:
            path: '/'
            port: 443
          initialDelaySeconds: 120
          timeoutSeconds: 3
          periodSeconds: 5
          failureThreshold: 7
      volumes:
      - name: qtumnfs
        persistentVolumeClaim:
          claimName: qtum-volume
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: qtum-volume
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: qtum-volume
  resources:
    requests:
      storage: 1Ti
