apiVersion: batch/v1
kind: Job
metadata:
  name: quantumworkspace-job
spec:
  template:
    metadata:
      name: quantumworkspace-job
    spec:
      containers:
      - name: quantumworkspace
        image: elijun831/quantumworkspace:3.0.0
        command: ["/bin/bash", "/start.sh"]
      restartPolicy: Never
