apiVersion: batch/v1
kind: Job
metadata:
  name: quantumworkspace
spec:
  template:
    metadata:
      name: quantumworkspace
    spec:
      containers:
      - name: quantumworkspace
        image: elijun831/quantumworkspace:2.0.1
        command: ["pipenv", "run", "jupyter", "lab", "--notebook-dir=/notebooks", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
      restartPolicy: Never
