apiVersion: batch/v1
kind: Job
metadata:
  name: quantumworkspace
spec:
  template:
    metadata:
      name: quantumworkspace
    spec:
      containers:
      - name: quantumworkspace
        image: elijun831/quantumworkspace:2.0.4
        command: ["/bin/bash", "/start.sh"]
      restartPolicy: Never
