# For creating the ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: quantumworkspace
  labels:
    app: quantumworkspace
spec:
  replicas: 3 # Could be any number
  selector:
    matchLabels:
      app: quantumworkspace
  template:
    metadata:
      labels:
        app: quantumworkspace
    spec:
      containers:
      - name: quantumworkspace
        image: elijun831/quantumworkspace:2.0.1
        command: ["pipenv", "run", "jupyter", "lab", "--notebook-dir=/notebooks", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
        ports:
        - containerPort: 8888
        - containerPort: 5678
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 2Gi
