# For creating the ReplicaSet
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: quantumworkspace-replicaset
  labels:
    app: quantumworkspace-replicaset
spec:
  replicas: 3 # Could be any number
  selector:
    matchLabels:
      app: quantumworkspace-replicaset
  template:
    metadata:
      labels:
        app: quantumworkspace-replicaset
    spec:
      containers:
      - name: quantumworkspace
        image: elijun831/quantumworkspace:2.0.4
        command: ["/bin/bash", "/start.sh"]
        ports:
        - containerPort: 8888
        - containerPort: 5678
        - containerPort: 443
        resources: # optional
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 2Gi
