version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "5678:5678"
      - "8080:8080"
      - "443:443"
      - "80:80"
    volumes:
      - ./notebooks:/notebooks
      - ./app:/app
      - ./logs:/logs
    user:
      - "appuser"
      - "root"
    environment:
      - DEBUG=1
      - JUPYTER_PORT=8888
