version: '2.0.1'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "5678:5678"
    volumes:
      - ./app:/app
      - ./notebooks:/notebooks
    user: appuser
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDEBUG=1
