services:
  web:
    build: ./
    image: elijun831/quantumworkspace:3.0.0
    networks:
      - mynetwork
    volumes:
      - /notebooks:/notebooks 

  quantumworkspace:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "5678:5678"
    volumes:
      - /notebooks:/notebooks
    networks:
      - mynetwork
    hostname: quantumworkspace

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus 

  fluentd:
    image: fluent/fluentd:latest 
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf

  elasticsearch:
    image: elasticsearch:latest 
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data 

  kibana:
    image: kibana:latest 
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml 

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8443:443"
      - "443:443"
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGX_HTTP_PORT=80
      - NGX_HTTPS_PORT=443
      - JUPYTER_HOST=web
      - JUPYTER_PORT=8888
    networks:
      - mynetwork
    depends_on:
      - quantumworkspace

networks:
  mynetwork:
    driver: bridge

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/home/user/data/prometheus"
  es_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/data/elasticsearch"

