version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./app:/home/appuser/app:rw
      - ./notebooks:/notebooks
    user: "root"
    environment:
      - PUID=5678
      - PGID=5678

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - webapp
