version: '1.1.0'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./notebooks:/notebooks
    ports:
      - 8888:8888
      - 5678:5678
    user: appuser
    environment:
      - PYTHONDEBUG=1
