version: '2.0.3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
      - "${DEBUG_PORT:-5678}:5678" 
      - "${WEB_PORT:-8080}:8080"  
      - "${HTTP_PORT:-80}:80" 
    volumes:
      - ./app:/app
      - ./notebooks:/notebooks
    user: "${APP_USER:-appuser}" 
    environment:
      - PUID=${PUID}  
      - PGID=${PGID}  
      - PYTHONUNBUFFERED=1 
      - PYTHONDEBUG=1
