services:
  web:
    image: elijun831/quantumworkspace:3.0.0
    volumes:
      - /notebooks:/notebooks
    networks:
      - mynetwork
    build: .
    hostname: quantumworkspace
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  elasticsearch:
    image: elasticsearch:8.13.0
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - es_data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200" 
      - "9300:9300"
    networks:
      - mynetwork
    container_name: qtum_elasticsearch
    #depends_on:
    #restart: no

  fluentd:
    image: fluentd:latest
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
      - ./logs:/fluentd/logs
      - /var/log/nginx:/var/log/nginx
    #environment:
    ports:
      - "24224:24224" 
      - "24224:24224/udp"
    networks:
      - mynetwork
    depends_on:
      - elasticsearch
    #restart: no

  kibana:
    image: kibana:8.13.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - mynetwork
    depends_on:
      - elasticsearch
    #restart: no

  nginx:
    image: nginx:latest
    volumes:
      #- ./certs:/etc/nginx/certs
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - JUPYTER_PORT=8888 
      - JUPYTER_HOST=web  
    ports:
      - "8080:80"   
      - "443:443"
      - "8443:8443"
    networks:
      - mynetwork
    depends_on:
      - web
    #restart: no

networks:
  mynetwork:
    driver: bridge

volumes:
  es_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/data/elasticsearch"

