version: '3.8'

services:
  web:
    build: ./
    image: elijun9831/quantumworkspace:3.0.0
    networks:
      - mynetwork
    volumes:
      - /notebooks:/notebooks  # Adjust as needed

  nginx:
    image: nginx:latest
    ports:
      - "8888:8888"
      - "5678:5678"
      - "8080:8080"
      - "8443:443"
      - "443:443"
      - "80:80"
      - "22:22"
      - "53:53"
      - "68:68"
    networks:
      - mynetwork
    depends_on:
      - web
    environment:
      - NGX_HTTP_PORT=80
      - NGX_HTTPS_PORT=443
      - JUPYTER_HOST=web  # Or internal IP of 'web' service 
      - JUPYTER_PORT=8888

networks:
  mynetwork:
    driver: bridge
