version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${JUPYTER_PORT:-8888}:8888"
      - "${DEBUG_PORT:-5678}:5678"
    volumes:
      - ./app:/app:rw,uid=${PUID},gid=${PGID}
      - ./notebooks:/notebooks
    user: "${APP_USER:-appuser}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
