version: '3.8'

services:
  web:
    build: ./
    image: elijun9831/quantumworkspace:2.0.5
    networks:
      - mynetwork
    volumes:
      - /notebooks:/notebooks  # Adjust as needed

  nginx:
    image: nginx:1.23-alpine 
    ports:
      - "8080:8080"
      - "80:80"
      - "8443:443"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mynetwork
    depends_on:
      - web
    environment:
      - NGX_HTTP_PORT=80  
      - NGX_HTTPS_PORT=443
      - JUPYTER_HOST=web  # Or internal IP of 'web' service 
      - JUPYTER_PORT=8888 

networks:
  mynetwork:
    driver: bridge
