version: '3.8'

services:
  web:
    build: ./
    image: elijun831/quantumworkspace:3.0.0
    networks:
      - mynetwork
    volumes:
      - /notebooks:/notebooks
    hostname: quantumworkspace

  elasticsearch:
    image: elasticsearch:8.13.0
    environment:
      discovery.type: single-node
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data 
    networks:
      - mynetwork

  fluentd:
    image: fluentd:latest
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./logs:/fluentd/logs
      - /var/log/nginx:/var/log/nginx 
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24225:24224"
      - "24224:24224/udp"
    networks:
      - mynetwork

  kibana:
    image: kibana:8.13.0
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml 
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8443:443"
      - "443:443"
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGX_HTTP_PORT=80
      - NGX_HTTPS_PORT=443
      - JUPYTER_HOST=web
      - JUPYTER_PORT=8888
    networks:
      - mynetwork
    depends_on:
      - web

networks:
  mynetwork:
    driver: bridge

volumes:
  es_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/data/elasticsearch"

