version: '3.8'

services:
  web:
    build: ./
    image: elijun9831/quantumworkspace:2.0.5
    networks:
      - mynetwork
    volumes:
      - /notebooks

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "80:80"
      - "8443:443"
      - "443:443"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mynetwork
    depends_on:
      - web

networks:
  mynetwork:
    driver: bridge
