version: '3.8'

services:
  web:
    build: ./
    image: elijun9831/quantumworkspace:2.0.5
    networks:
      - mynetwork
    volumes:
      - /notebooks

  quantumworkspace:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "5678:5678"
    volumes:
      - /notebooks
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "80:80"
      - "8443:443"
      - "443:443"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - mynetwork
    depends_on:
      - quantumworkspace
    links:
      - quantumworkspace

networks:
  mynetwork:
    driver: bridge
