services:
  web:
    image: elijun831/quantumworkspace:3.0.0
    volumes:
      - /notebooks:/notebooks
    networks:
      - mynetwork
    build: ./
    hostname: quantumworkspace

  elasticsearch:
    image: elasticsearch:8.13.0
    volumes:
      - ./elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yaml
      - es_data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
    ports:
      - "${ES_PORT}:${ES_PORT}"
    networks:
      - mynetwork
    #depends_on:
    #restart: no

  fluentd:
    image: fluentd:latest
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf
      - ./logs:/fluentd/logs
      - /var/log/nginx:/var/log/nginx
    #environment:
    ports:
      - "${FLUENTD_PORT}:${FLUENTD_PORT}"
      - "${FLUENTD_PORT}:24224/udp"
    networks:
      - mynetwork
    depends_on:
      - elasticsearch
    #restart: no

  kibana:
    image: kibana:8.13.0
    volumes:
      - ./kibana.yaml:/usr/share/kibana/config/kibana.yaml
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - "${KIBANA_PORT}:${KIBANA_PORT}"
    networks:
      - mynetwork
    depends_on:
      - elasticsearch
    #restart: no

  nginx:
    image: nginx:latest
    volumes:
      - ./certs:/etc/nginx/certs
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGX_HTTP_PORT=${NGINX_HTTP_PORT}
      - NGX_HTTPS_PORT=${NGINX_HTTPS_PORT}
      - JUPYTER_HOST=web
      - JUPYTER_PORT=${JUPYTER_PORT}
    ports:
      - "${NGINX_HOST_PORT}:8080"
      - "${NGINX_HTTPS_PORT}:443"
      - "443:443"
      - "80:80"
    networks:
      - mynetwork
    depends_on:
      - web
    #restart: no

networks:
  mynetwork:
    driver: bridge

volumes:
  es_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/mnt/data/elasticsearch"

