version: '2.0.2'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "5678:5678"
      - "8080:8080"
      - "80:80"
    volumes:
      - ./notebooks:/notebooks
    user: "appuser"
