services:
  web:
    build: ./
    image: elijun831/quantumworkspace:3.0.0
    networks:
      - mynetwork
    volumes:
      - /notebooks:/notebooks  # Adjust as needed

  quantumworkspace:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "5678:5678"
    volumes:
      - /notebooks
    networks:
      - mynetwork
    hostname: quantumworkspace

  prometheus:
    image: prom/prometheus:latest  # Or specify your version
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  fluentd:
    image: fluent/fluentd:latest  # Or specify your version
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd.conf:/fluentd/etc/fluentd.conf

  elasticsearch:
    image: elasticsearch:latest  # Or specify your version
    ports:
      - "9200:9200"
    volumes: 
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: kibana:latest   # Or specify your version
    ports:
      - "5601:5601"
    volumes:
       - ./kibana.yml:/usr/share/kibana/config/kibana.yml 

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8443:443"
      - "443:443"
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGX_HTTP_PORT=80
      - NGX_HTTPS_PORT=443
      - JUPYTER_HOST=web  # Or internal IP of 'web' service 
      - JUPYTER_PORT=8888
    networks:
      - mynetwork
    depends_on:
      - quantumworkspace
    links:
      - quantumworkspace

networks:
  mynetwork:
    driver: bridge
