version: '2.0.3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "5678:5678"
      - "8080:8080"
      - "80:80"
    volumes:
      - ./notebooks:/notebooks
      - ./app:/app
      - ./logs:/logs
    user: 
      - "appuser"
      - "root"
    environment:
      - DEBUG=1
      - JUPYTER_PORT=8888
    command: ["bin/bash"]
