version: '3.8'

services:
  web:
    build: ./
    image: elijun831/quantumworkspace:3.0.0
    networks:
      - mynetwork
    volumes:
      - /notebooks:/notebooks  # Adjust as needed

  quantumworkspace:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
      - "5678:5678"
    volumes:
      - /notebooks
    networks:
      - mynetwork
    hostname: quantumworkspace

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
      - "8443:443"
      - "443:443"
      - "80:80"
    volumes:
      - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGX_HTTP_PORT=80
      - NGX_HTTPS_PORT=443
      - JUPYTER_HOST=web  # Or internal IP of 'web' service 
      - JUPYTER_PORT=8888
    networks:
      - mynetwork
    depends_on:
      - quantumworkspace
    links:
      - quantumworkspace

networks:
  mynetwork:
    driver: bridge
