input {
  file {
    path => "/var/log/nginx/access.log" 
    start_position => "beginning" 
    sincedb_path => "/dev/null"  
  }
}

filter {
  grok {
    match => { "message" => "%{COMBINEDAPACHELOG}" }
  }
  date {
    match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ] # Adjust if needed
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"] 
    index => "nginx-logs-%{+YYYY.MM.dd}" 
  }
}
